### ISSUE TITLE
Questions about CP-nets semantics

### ISSUE THREAD

**Issue by q13926117923** [spykard/cp-networks#1]
I am confused about the meaning of the input and output of the CP-nets solving algorithm. 
For example: input is dataset'sushi_30Users_10000Comparisons.dat' 
We have 10000 Comparisons from 30 Users, Do we need to build a CP-nets for each user? That is,  build 30 CP-nets to represent the dependencies between the issue (attribute) in their mind? 🤔
I would be very grateful for your answers!

**Comment by spykard** [comment]
If I remember correctly, we do need to build a CP-net for each user, for example the `movieLensDataset` example uses a single user to calculate the CP-net, i.e. user with ID 4222.

**Comment by q13926117923** [comment]
Thanks for your reply~
